blank_issues_enabled: true
contact_links:
  - name: ðŸ“º Diolinux YouTube Channel
    url: https://youtube.com/Diolinux
    about: Watch tutorials and updates about PhotoGIMP
  - name: ðŸ’¬ Discussions
    url: https://github.com/Diolinux/PhotoGIMP/discussions
    about: Ask questions and discuss with the community
